name: OSX Build

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [OSX]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v6
    - name: build
      run: bash buildPetriSpot.sh
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          branch: Inv-OSX # The branch the action should deploy to.
          folder: website/ # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch 
          single-commit: true
