name: windows build

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [Windows]

jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v6
    - name: install packages
      run:  C:\msys64\usr\bin\bash -lc "PATH+=:/mingw64/bin ; pacman --noconfirm -S base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-autotools p7zip mingw-w64-x86_64-expat base-devel libtool"
    - name: configure and make
      run:  C:\msys64\usr\bin\bash -lc "PATH+=:/mingw64/bin ; cd /D/a/PetriSpot/PetriSpot/Petri  ; (autoreconf -vfi && ./configure --prefix=/D/a/PetriSpot/PetriSpot/usr/local/ --enable-nolto --enable-mingw-native && make && make install) || cat config.log"
    - name: package zip
      run:  C:\msys64\usr\bin\bash -lc "PATH+=:/mingw64/bin ; cd /D/a/PetriSpot/PetriSpot  ;  mkdir site ; strip -s Petri/src/petri32.exe ; strip -s Petri/src/petri64.exe ; strip -s Petri/src/petri128.exe ; cp Petri/src/petri*.exe site/; "
    - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
      uses: actions/upload-artifact@v7
      with:
        name: site
        path: site/
    
  deploy:
    needs: [build] # The second job must depend on the first one to complete before running, and uses ubuntu-latest instead of windows.

    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Download Artifacts  # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v7
        with:
          name: site

      - name: move to website
        run: ls -lah ; mkdir -p windows ; cp petri*.exe windows ;  ls -lah windows/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: Inv-Windows
          folder: windows/ # The deployment folder should match the name of the artifact. Even though our project builds into the 'build' folder the artifact name of 'site' must be placed here.
          clean: true # Automatically remove deleted files from the deploy branch
          single-commit: true 
